preview:
  # LEVEL:
  # 0- Show nothing
  # 1- Show only mandatory stats
  # 2- Show mandatory + high-roll stats
  # 3- Show all stats

  legendary:
    level: 2
    min_percent: 70
    min_percent_mandatory: 50
  other:
    level: 2
    min_percent: 50
    min_percent_mandatory: 20


  melee_weps: &m_wep [attack damage] # helper node
  melee_armor: &m_armor [strength, dex, end] # helper node
  mandatory_stats: # "(partial) equip name" : [list of (partial) mandatory stat names]
    "": [block, parry]
    staff: [magic damage, depr prof, int, wis]

    fiery staff: [fire edb]
    arctic staff: [cold edb]
    temp staff: [wind edb]
    shock staff: [elec edb]
    hallowed staff: [holy edb]
    demon staff: [dark edb]

    surtr: [fire edb, elem prof]
    nifl: [cold edb, elem prof]
    freyr: [wind edb, elem prof]
    mjo: [elec edb, elem prof]
    heimd: [holy edb, div prof]
    fenr: [dark edb, forb prof]

    the elem: [elem prof]
    the demon: [forb prof]
    the heaven: [div prof]

    waki: *m_wep
    axe: *m_wep
    club: *m_wep
    rapier: *m_wep
    sword: *m_wep
    estoc: *m_wep
    mace: *m_wep
    katana: *m_wep

    leather: *m_armor
    shade: *m_armor
    plate: *m_armor
    power: *m_armor

  highlights:
    slaughter: &red ff0000
    legendary: *red
    shade: *red
    fleet: *red
    reinforced: *red
    force: *red
    phase: *red
    power: *red
    savage: *red
    peerless: ffa500

  abbreviations:
    Block Chance: BLK
    Attack Damage: ADB
    Magic Damage: MDB
    Attack Crit Chance: Pcrit%
    Magic Crit Chance: Mcrit%
    Attack Crit Damage: Pcrit Dmg
    Magic Crit Damage: Mcrit Dmg
    Attack Accuracy: Pacc
    Magic Accuracy: Macc

    Elemental PROF: Elem Prof
    Supportive PROF: Supp Prof
    Deprecating PROF: Depr Prof
    Divine PROF: Holy Prof
    Forbidden PROF: Dark Prof

    Wisdom: WIS
    Intelligence: INT
    Agility: AGI
    Endurance: END
    Strength: STR
    Dexterity: DEX

    Interference: Intf

    Physical Mitigation: Pmit
    Magical Mitigation: Mmit
    Crushing MIT: Crush
    Slashing MIT: Slash
    Piercing MIT: Pierc

    Parry Chance: Parry
    Evade Chance: Evade
    Resist Chance: Resist
    Counter-Resist: CR
    Attack Speed: AS
    Casting Speed: CS